dist: trusty
sudo: false

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov codecov flake8

script:
  - pytest --cov=webssh
  - flake8 --exclude='.git'

after_success:
  - codecov
